---
--- Generated by Luanalysis
--- Created by garrettg.
--- DateTime: 2023-05-07 10:10 p.m.
---
local opts = { noremap = true, silent = true }


-- Shorten function name
local map = vim.api.nvim_set_keymap
--Remap space as leader key
map("", "<Space>", "<Nop>", opts)
vim.g.mapleader = " "
vim.g.maplocalleader = " "

-- Modes
--   normal_mode = "n",
--   insert_mode = "i",
--   visual_mode = "v",
--   visual_block_mode = "x",
--   term_mode = "t",
--   command_mode = "c",

-- Some custom mappins that seem hella useful
--

map("v", "J", ":m '>+1<CR>gv=gv", opts)
map("v", "K", ":m '<-2<CR>gv=gv", opts)

-- Telescope and buffer things below it seems

map("n", "<leader>q", "<CMD>Bdelete<CR>", opts)

map(
  "n",
  "<leader>fb",
  "<Cmd>Telescope file_browser path=%:p:h select_buffer=true<CR>",
  opts
)

map(
  "n",
  "<leader>ff",
  "<Cmd>Telescope find_files<CR>",
  opts
)

map(
  "n",
  "<leader>fr",
  "<Cmd>Telescope oldfiles<CR>",
  opts
)

map(
  "n",
  "<leader><leader>",
  "<Cmd>Telescope oldfiles<CR>",
  opts
)


-- Move to previous/next
map('n', '<A-j>', '<Cmd>BufferPrevious<CR>', opts)
map('n', '<A-k>', '<Cmd>BufferNext<CR>', opts)
-- Re-order to previous/next
map('n', '<A-J>', '<Cmd>BufferMovePrevious<CR>', opts)
map('n', '<A-K>', '<Cmd>BufferMoveNext<CR>', opts)
-- Goto buffer in position...
map('n', '<A-1>', '<Cmd>BufferGoto 1<CR>', opts)
map('n', '<A-2>', '<Cmd>BufferGoto 2<CR>', opts)
map('n', '<A-3>', '<Cmd>BufferGoto 3<CR>', opts)
map('n', '<A-4>', '<Cmd>BufferGoto 4<CR>', opts)
map('n', '<A-5>', '<Cmd>BufferGoto 5<CR>', opts)
map('n', '<A-6>', '<Cmd>BufferGoto 6<CR>', opts)
map('n', '<A-7>', '<Cmd>BufferGoto 7<CR>', opts)
map('n', '<A-8>', '<Cmd>BufferGoto 8<CR>', opts)
map('n', '<A-9>', '<Cmd>BufferGoto 9<CR>', opts)
map('n', '<A-0>', '<Cmd>BufferLast<CR>', opts)
-- Pin/unpin buffer
map('n', '<A-p>', '<Cmd>BufferPin<CR>', opts)
-- Close buffer
map('n', '<A-c>', '<Cmd>BufferClose<CR>', opts)
-- Wipeout buffer
--                 :BufferWipeout
-- Close commands
--                 :BufferCloseAllButCurrent
--                 :BufferCloseAllButPinned
--                 :BufferCloseAllButCurrentOrPinned
--                 :BufferCloseBuffersLeft
--                 :BufferCloseBuffersRight
-- Magic buffer-picking mode
map('n', '<C-p>', '<Cmd>BufferPick<CR>', opts)
-- Sort automatically by...

map('n', '<Space>bb', '<Cmd>BufferOrderByBufferNumber<CR>', opts)
map('n', '<Space>bd', '<Cmd>BufferOrderByDirectory<CR>', opts)
map('n', '<Space>bl', '<Cmd>BufferOrderByLanguage<CR>', opts)
map('n', '<Space>bw', '<Cmd>BufferOrderByWindowNumber<CR>', opts)

map('n', "<leader>xo", "<CMD>NvimTreeOpen<CR>", opts)
map('n', "<leader>xc", "<CMD>NvimTreeClose<CR>", opts)

-- Debugging
--

local function widget()
  local widgets = require('dap.ui.widgets');
  local sidebar = widgets.sidebar(widgets.scopes);
  sidebar.open();
end

map('n', "<leader>db", "<CMD>DapToggleBreakpoint<CR>", opts)
map('n', "<leader>do", "<CMD>DapStepOver<CR>", opts)
map('n', "<leader>di", "<CMD>DapStepInto<CR>", opts)
map('n', "<leader>dc", "<CMD>DapContinue<CR>", opts)
map('n', "<leader>dt", "<CMD>DapTerminate<CR>", opts)
